workflows:
  ios-zishop:
    name: iOS ZiShop Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
    environment:
      vars:
        BUNDLE_ID: com.startindev.zishop
      node: 18
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Install Capacitor CLI
        script: |
          npm install -g @capacitor/cli@latest
      - name: Update Capacitor to latest
        script: |
          npm install @capacitor/core@latest @capacitor/cli@latest @capacitor/ios@latest
      - name: Add iOS platform with proper deployment target
        script: |
          npx cap add ios
          # Set minimum deployment target to iOS 13
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 11.0/IPHONEOS_DEPLOYMENT_TARGET = 13.0/' ios/App.xcodeproj/project.pbxproj
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Update Bundle ID
        script: |
          sed -i '' "s/com.getcapacitor.myapp/$BUNDLE_ID/g" ios/App/App/Info.plist
      - name: Update CocoaPods and install
        script: |
          gem install cocoapods
          cd ios/App && pod install --repo-update
      - name: Build for simulator (test)
        script: |
          cd ios
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -configuration Debug \
                     -destination 'platform=iOS Simulator,name=iPhone 14' \
                     build
    artifacts:
      - ios/build/Build/Products/**/*.app
    publishing:
      email:
        recipients:
          - bahriwass@gmail.com
        notify:
          success: true
          failure: true