workflows:
  ios-zishop:
    name: iOS ZiShop Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
    environment:
      vars:
        BUNDLE_ID: com.startindev.zishop
      node: 18
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Install Capacitor CLI
        script: |
          npm install -g @capacitor/cli@latest
      - name: Add iOS platform
        script: |
          npx cap add ios
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Update Bundle ID
        script: |
          sed -i '' "s/com.getcapacitor.myapp/$BUNDLE_ID/g" ios/App/App/Info.plist
      - name: Install CocoaPods
        script: |
          cd ios/App && pod install --repo-update
      - name: Build for simulator (test)
        script: |
          cd ios
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -configuration Debug \
                     -destination 'platform=iOS Simulator,name=iPhone 14' \
                     build
    artifacts:
      - ios/build/Build/Products/**/*.app
    publishing:
      email:
        recipients:
          - bahriwass@gmail.com
        notify:
          success: true
          failure: true