workflows:
  ios-zishop:
    name: iOS ZiShop Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: master
          include: true
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.startindev.zishop
      vars:
        XCODE_WORKSPACE: "ios/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 18
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Build web application
        script: |
          npm run build
      - name: Install Capacitor CLI
        script: |
          npm install -g @capacitor/cli@latest
      - name: Initialize iOS platform
        script: |
          npx cap add ios || echo "iOS platform already exists"
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install
      - name: Build iOS app
        script: |
          cd ios
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -configuration Debug \
                     -destination generic/platform=iOS \
                     -archivePath App.xcarchive \
                     archive
      - name: Export IPA
        script: |
          cd ios
          xcodebuild -exportArchive \
                     -archivePath App.xcarchive \
                     -exportPath ./build \
                     -exportOptionsPlist ExportOptions.plist
    artifacts:
      - ios/build/*.ipa
      - ios/*.xcarchive
    publishing:
      email:
        recipients:
          - contact@startindev.zishop
        notify:
          success: true
          failure: true