workflows:
  ios-zishop:
    name: ZiShop iOS Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
    environment:
      vars:
        BUNDLE_ID: com.startindev.zishop
      node: 20
      cocoapods: default
    scripts:
      - name: Check Node version
        script: |
          node --version
          npm --version
      - name: Install dependencies
        script: |
          npm install
      - name: Build web application
        script: |
          npm run build
          echo "Web build completed:"
          ls -la dist/public/
      - name: Install latest Capacitor
        script: |
          npm install @capacitor/core@latest @capacitor/cli@latest @capacitor/ios@latest
          npx cap --version
      - name: Add iOS platform
        script: |
          npx cap add ios
          echo "iOS platform added:"
          ls -la ios/
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Verify Xcode project
        script: |
          ls -la ios/App/
          if [ -f "ios/App.xcodeproj/project.pbxproj" ]; then
            echo "Xcode project found!"
            # Update deployment target
            sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9]*\.[0-9]*/IPHONEOS_DEPLOYMENT_TARGET = 13.0/g' ios/App.xcodeproj/project.pbxproj
          else
            echo "Xcode project not found, checking workspace..."
            ls -la ios/App/App.xcworkspace/
          fi
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install
      - name: Test build (simulator)
        script: |
          echo "Looking for Xcode files..."
          find ios -name "*.xcworkspace" -o -name "*.xcodeproj" | head -5
          
          cd ios/App
          if [ -d "App.xcworkspace" ]; then
            echo "Using workspace build..."
            xcodebuild -workspace App.xcworkspace -scheme App -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 14' build
          elif [ -d "App.xcodeproj" ]; then
            echo "Using project build..."
            xcodebuild -project App.xcodeproj -scheme App -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 14' build
          else
            echo "No Xcode project found! Listing contents:"
            ls -la
            exit 1
          fi
    artifacts:
      - ios/**/*.app
      - ios/**/*.xcarchive
    publishing:
      email:
        recipients:
          - bahriwass@gmail.com
        notify:
          success: true
          failure: true